"""Initial migration with all current tables including JSONB data column

Revision ID: db8b04f8e267
Revises: 
Create Date: 2025-06-07 11:47:19.711670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db8b04f8e267'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speaker_event_meeting_absolute_time'), table_name='speaker_events')
    op.drop_index(op.f('ix_speaker_event_participant_meeting'), table_name='speaker_events')
    op.drop_index(op.f('ix_speaker_event_session_time'), table_name='speaker_events')
    op.drop_index(op.f('ix_speaker_events_absolute_timestamp'), table_name='speaker_events')
    op.drop_index(op.f('ix_speaker_events_event_type'), table_name='speaker_events')
    op.drop_index(op.f('ix_speaker_events_id'), table_name='speaker_events')
    op.drop_index(op.f('ix_speaker_events_meeting_id'), table_name='speaker_events')
    op.drop_index(op.f('ix_speaker_events_participant_id_meet'), table_name='speaker_events')
    op.drop_index(op.f('ix_speaker_events_session_uid'), table_name='speaker_events')
    op.drop_table('speaker_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('participant_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('participant_id_meet', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('event_type', postgresql.ENUM('SPEAKER_START', 'SPEAKER_END', name='speakereventtype'), autoincrement=False, nullable=False),
    sa.Column('client_timestamp_ms', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('server_timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('absolute_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('speaker_events_meeting_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('speaker_events_pkey'))
    )
    op.create_index(op.f('ix_speaker_events_session_uid'), 'speaker_events', ['session_uid'], unique=False)
    op.create_index(op.f('ix_speaker_events_participant_id_meet'), 'speaker_events', ['participant_id_meet'], unique=False)
    op.create_index(op.f('ix_speaker_events_meeting_id'), 'speaker_events', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_speaker_events_id'), 'speaker_events', ['id'], unique=False)
    op.create_index(op.f('ix_speaker_events_event_type'), 'speaker_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_speaker_events_absolute_timestamp'), 'speaker_events', ['absolute_timestamp'], unique=False)
    op.create_index(op.f('ix_speaker_event_session_time'), 'speaker_events', ['session_uid', 'client_timestamp_ms'], unique=False)
    op.create_index(op.f('ix_speaker_event_participant_meeting'), 'speaker_events', ['meeting_id', 'participant_id_meet', 'absolute_timestamp'], unique=False)
    op.create_index(op.f('ix_speaker_event_meeting_absolute_time'), 'speaker_events', ['meeting_id', 'absolute_timestamp'], unique=False)
    # ### end Alembic commands ### 